### ISSUE TITLE
Hello, I would like to ask why this problem keeps occurring and there is no way to fix it

### ISSUE THREAD

**Issue by 123456789qwerfds** [ruiking04/CutAddPaste#1]
Traceback (most recent call last):
  File "cutAddPaste.py", line 110, in <module>
    train_dl, val_dl, test_dl, test_anomaly_window_num = data_generator(train_data, test_data, train_labels,
  File "/data/wxc/CutAddPaste-main/dataloader/dataset.py", line 83, in data_generator
    train_aug_x = cut_add_paste_outlier(train_origin, configs)
  File "/data/wxc/CutAddPaste-main/dataloader/generate_negative.py", line 162, in cut_add_paste_outlier
    cut_data[:, item] += slope
ValueError: operands could not be broadcast together with shapes (8,) (16,) (8,)

**Comment by ruiking04** [comment]
Thank you for following our work.

We set breakpoints and ran the program on the SWaT dataset but did not find the above problems.
Below is a screenshot of the running program under debugging.
This code means randomly selecting several dimensions in a multi-dimensional time series to add trend items.
We guess it is a Numpy version problem, our version is v1.24.3.

<img width="988" alt="1725959155046" src="https://github.com/user-attachments/assets/fb59636d-4d15-4bf6-937a-0a8dfebd917a">

**Comment by ruiking04** [comment]
Sorry, we found the problem because we forgot to modify the WADI hyperparameters. According to the paper, it should be as follows:
```
self.features_len = 6
self.window_size = 32
self.time_step = 16
```
The source code has been updated.
